// Popular ETF & Stock Auto-complete Database with Latest Closing/Market Prices (최종 장 마감/현재 기준가 탑재)
const POPULAR_STOCKS = [
  // 연금저축 & ISA 대표 ETF (국내상장 해외/국내 ETF)
  { name: 'TIGER 미국S&P500', ticker: '360750', currency: 'KRW', defaultAccount: 'pension', defaultPrice: 26055 },
  { name: 'ACE 미국S&P500', ticker: '360200', currency: 'KRW', defaultAccount: 'pension', defaultPrice: 19820 },
  { name: 'KODEX 미국S&P500TR', ticker: '379800', currency: 'KRW', defaultAccount: 'pension', defaultPrice: 19250 },
  { name: 'TIGER 미국나스닥100', ticker: '133690', currency: 'KRW', defaultAccount: 'pension', defaultPrice: 124800 },
  { name: 'ACE 미국나스닥100', ticker: '367380', currency: 'KRW', defaultAccount: 'pension', defaultPrice: 17950 },
  { name: 'KODEX 미국나스닥100', ticker: '379810', currency: 'KRW', defaultAccount: 'pension', defaultPrice: 18100 },
  { name: 'TIGER 미국배당다우존스', ticker: '458730', currency: 'KRW', defaultAccount: 'isa', defaultPrice: 11180 },
  { name: 'ACE 미국배당다우존스', ticker: '402970', currency: 'KRW', defaultAccount: 'isa', defaultPrice: 12350 },
  { name: 'SOL 미국배당다우존스', ticker: '446720', currency: 'KRW', defaultAccount: 'isa', defaultPrice: 10450 },
  { name: 'TIGER 미국테크TOP10 INDXX', ticker: '381170', currency: 'KRW', defaultAccount: 'pension', defaultPrice: 19500 },
  { name: 'ACE 미국빅테크TOP7 PLUS', ticker: '465580', currency: 'KRW', defaultAccount: 'pension', defaultPrice: 16800 },
  { name: 'TIGER 미국필라델피아반도체나스닥', ticker: '381180', currency: 'KRW', defaultAccount: 'pension', defaultPrice: 21200 },
  { name: 'ACE 미국반도체15가치주', ticker: '438320', currency: 'KRW', defaultAccount: 'pension', defaultPrice: 13500 },
  { name: 'KODEX 미국서학개미', ticker: '472150', currency: 'KRW', defaultAccount: 'pension', defaultPrice: 12800 },
  { name: 'TIGER 인도니프티50', ticker: '453810', currency: 'KRW', defaultAccount: 'pension', defaultPrice: 14650 },
  { name: 'ACE 인도컨슈머파워', ticker: '480310', currency: 'KRW', defaultAccount: 'pension', defaultPrice: 13200 },
  { name: 'KODEX 200', ticker: '069500', currency: 'KRW', defaultAccount: 'isa', defaultPrice: 35800 },
  { name: 'TIGER 200', ticker: '102110', currency: 'KRW', defaultAccount: 'isa', defaultPrice: 35850 },
  { name: 'KODEX 코스닥150', ticker: '229200', currency: 'KRW', defaultAccount: 'isa', defaultPrice: 12400 },
  { name: 'KODEX CD금리액티브(합성)', ticker: '459580', currency: 'KRW', defaultAccount: 'isa', defaultPrice: 1045000 },
  { name: 'TIGER KOFR금리액티브(합성)', ticker: '449170', currency: 'KRW', defaultAccount: 'pension', defaultPrice: 106000 },

  // 국내 대표 개별주 (최신 종가 기준)
  { name: '삼성전자', ticker: '005930', currency: 'KRW', defaultAccount: 'isa', defaultPrice: 77500 },
  { name: '삼성전자우', ticker: '005935', currency: 'KRW', defaultAccount: 'isa', defaultPrice: 62000 },
  { name: 'SK하이닉스', ticker: '000660', currency: 'KRW', defaultAccount: 'isa', defaultPrice: 184500 },
  { name: 'LG에너지솔루션', ticker: '373220', currency: 'KRW', defaultAccount: 'isa', defaultPrice: 395000 },
  { name: '현대차', ticker: '005380', currency: 'KRW', defaultAccount: 'isa', defaultPrice: 242000 },
  { name: '기아', ticker: '000270', currency: 'KRW', defaultAccount: 'isa', defaultPrice: 112000 },
  { name: '삼성바이오로직스', ticker: '207940', currency: 'KRW', defaultAccount: 'isa', defaultPrice: 890000 },
  { name: 'NAVER', ticker: '035420', currency: 'KRW', defaultAccount: 'isa', defaultPrice: 172000 },
  { name: '카카오', ticker: '035720', currency: 'KRW', defaultAccount: 'isa', defaultPrice: 38500 },
  { name: '셀트리온', ticker: '068270', currency: 'KRW', defaultAccount: 'isa', defaultPrice: 198000 },
  { name: 'KB금융', ticker: '105560', currency: 'KRW', defaultAccount: 'isa', defaultPrice: 86500 },
  { name: '신한지주', ticker: '055550', currency: 'KRW', defaultAccount: 'isa', defaultPrice: 54000 },
  { name: 'POSCO홀딩스', ticker: '005490', currency: 'KRW', defaultAccount: 'isa', defaultPrice: 368000 },

  // 미국 대표 주식 (최신 종가 기준, USD)
  { name: 'APPLE (애플)', ticker: 'AAPL', currency: 'USD', defaultAccount: 'usStock', defaultPrice: 228.2 },
  { name: 'MICROSOFT (마이크로소프트)', ticker: 'MSFT', currency: 'USD', defaultAccount: 'usStock', defaultPrice: 442.5 },
  { name: 'NVIDIA (엔비디아)', ticker: 'NVDA', currency: 'USD', defaultAccount: 'usStock', defaultPrice: 125.8 },
  { name: 'ALPHABET CLASS A (구글)', ticker: 'GOOGL', currency: 'USD', defaultAccount: 'usStock', defaultPrice: 168.4 },
  { name: 'AMAZON (아마존)', ticker: 'AMZN', currency: 'USD', defaultAccount: 'usStock', defaultPrice: 186.2 },
  { name: 'META PLATFORMS (메타)', ticker: 'META', currency: 'USD', defaultAccount: 'usStock', defaultPrice: 512.0 },
  { name: 'TESLA (테슬라)', ticker: 'TSLA', currency: 'USD', defaultAccount: 'usStock', defaultPrice: 243.5 },
  { name: 'BROADCOM (브로드컴)', ticker: 'AVGO', currency: 'USD', defaultAccount: 'usStock', defaultPrice: 165.0 },
  { name: 'TAIWAN SEMICONDUCTOR (TSMC)', ticker: 'TSM', currency: 'USD', defaultAccount: 'usStock', defaultPrice: 174.0 },
  { name: 'BERKSHIRE HATHAWAY (버크셔)', ticker: 'BRK.B', currency: 'USD', defaultAccount: 'usStock', defaultPrice: 452.0 },
  { name: 'ELI LILLY (일라이릴리)', ticker: 'LLY', currency: 'USD', defaultAccount: 'usStock', defaultPrice: 948.0 },
  { name: 'JPMORGAN CHASE (JP모건)', ticker: 'JPM', currency: 'USD', defaultAccount: 'usStock', defaultPrice: 215.0 },

  // 미국 대표 직투 ETF (최신 종가 기준, USD)
  { name: 'SPDR S&P 500 ETF (SPY)', ticker: 'SPY', currency: 'USD', defaultAccount: 'usStock', defaultPrice: 562.0 },
  { name: 'VANGUARD S&P 500 ETF (VOO)', ticker: 'VOO', currency: 'USD', defaultAccount: 'usStock', defaultPrice: 515.5 },
  { name: 'INVESCO QQQ TRUST (QQQ)', ticker: 'QQQ', currency: 'USD', defaultAccount: 'usStock', defaultPrice: 482.0 },
  { name: 'SCHWAB US DIVIDEND EQUITY (SCHD)', ticker: 'SCHD', currency: 'USD', defaultAccount: 'usStock', defaultPrice: 83.6 },
  { name: 'VANGUARD TOTAL STOCK MARKET (VTI)', ticker: 'VTI', currency: 'USD', defaultAccount: 'usStock', defaultPrice: 274.0 },
  { name: 'ISHARES 20+ YEAR TREASURY BOND (TLT)', ticker: 'TLT', currency: 'USD', defaultAccount: 'usStock', defaultPrice: 98.5 },
  { name: 'JPMORGAN EQUITY PREMIUM INCOME (JEPI)', ticker: 'JEPI', currency: 'USD', defaultAccount: 'usStock', defaultPrice: 57.8 },
  { name: 'JPMORGAN NASDAQ EQUITY PREMIUM (JEPQ)', ticker: 'JEPQ', currency: 'USD', defaultAccount: 'usStock', defaultPrice: 54.2 },
  { name: 'PROSHARES ULTRAPRO QQQ (TQQQ)', ticker: 'TQQQ', currency: 'USD', defaultAccount: 'usStock', defaultPrice: 72.5 },
  { name: 'DIREXION DAILY SEMICONDUCTOR BULL 3X (SOXL)', ticker: 'SOXL', currency: 'USD', defaultAccount: 'usStock', defaultPrice: 42.0 }
];
